name: test
on: { pull_request: {}, push: { branches: [master, main] } }

jobs:
  getcidata:
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.output.outputs.environments }}
    steps:
      - id: output
        run: |
          envblob="$(curl -fsSL https://raw.githubusercontent.com/vapor/ci/main/pr-environments.json | jq -cMj '.')"
          echo "::set-output name=environments::${envblob}"


  test-redis:
    needs: getcidata
    strategy:
      fail-fast: false
      matrix:
        env: ${{ fromJSON(needs.getcidata.outputs.environments) }}
    runs-on: ${{ matrix.env.os }}
    container: ${{ matrix.env.image }}
    steps: 
      - name: Select toolchain
        uses: maxim-lobanov/setup-xcode@v1.2.1
        with:
          xcode-version: ${{ matrix.env.toolchain }}
        if: ${{ matrix.env.toolchain != '' }}
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Install Redis via Homebrew (Mac)
        if: ${{ startsWith(matrix.env.os, 'macos') }}
        run: brew install redis 

      - name: Install Redis via apt-get (Ubuntu)
        if: ${{ startsWith(matrix.env.os, 'ubuntu') }}
        run: apt-get update && apt-get install -y redis

      - name: Install Redis via ??? (Windows)
        if: ${{ startsWith(matrix.env.os, 'windows') }}
        run: echo NOT IMPLEMENTED; exit 1

      - name: Start Redis 1
        run: redis-server .github/redis1.conf
      - name: Start Redis 2
        run: redis-server .github/redis2.conf

      - name: Test Redis 1 connection
        run: redis-cli -u redis://localhost:6379/0 INFO
      - name: Test Redis 2 connection
        run: redis-cli -u redis://localhost:6380/0 INFO

      - name: Run 'RedisTests' tests with Thread Sanitizer
        timeout-minutes: 20
        run: swift test --enable-test-discovery --sanitize=thread --filter RedisTests

      - name: Run 'MultipleRedisTests' tests with Thread Sanitizer
        timeout-minutes: 20
        run: swift test --enable-test-discovery --sanitize=thread --filter MultipleRedisTests

  test-exports:
      name: Test exports
      runs-on: ubuntu-latest
      steps:
        - name: Check out Vapor
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Build
          run: swift build -Xswiftc -DBUILDING_DOCC